[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
